In [2]:
import pandas as pd
import csv 
import numpy as np

In [3]:
matches = pd.read_csv("../data/cleaned/international_matches_clean.csv")
elo = pd.read_csv("../data/cleaned/elo_ratings.csv")

In [4]:
matches.tail(20)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
34529,2026-07-02,Switzerland,Algeria,2.0,0.0,FIFA World Cup,Vancouver,Canada,True
34530,2026-07-03,Australia,Egypt,1.0,1.0,FIFA World Cup,Arlington,United States,True
34531,2026-07-03,Argentina,Cape Verde,3.0,2.0,FIFA World Cup,Miami Gardens,United States,True
34532,2026-07-03,Colombia,Ghana,1.0,0.0,FIFA World Cup,Kansas City,United States,True
34533,2026-07-04,Canada,Morocco,0.0,3.0,FIFA World Cup,Houston,United States,True
34534,2026-07-04,Paraguay,France,0.0,1.0,FIFA World Cup,Philadelphia,United States,True
34535,2026-07-05,Brazil,Norway,1.0,2.0,FIFA World Cup,East Rutherford,United States,True
34536,2026-07-05,Mexico,England,2.0,3.0,FIFA World Cup,Mexico City,Mexico,False
34537,2026-07-06,Portugal,Spain,0.0,1.0,FIFA World Cup,Dallas,United States,True
34538,2026-07-06,United States,Belgium,1.0,4.0,FIFA World Cup,Seattle,United States,False
34539,2026-07-07,Argentina,Egypt,3.0,2.0,FIFA World Cup,Atlanta,United States,True
34540,2026-07-07,Switzerland,Colombia,0.0,0.0,FIFA World Cup,Vancouver,Canada,True
34541,2026-07-09,France,Morocco,2.0,0.0,FIFA World Cup,Foxborough,United States,True
34542,2026-07-10,Spain,Belgium,2.0,1.0,FIFA World Cup,Inglewood,United States,True
34543,2026-07-11,Norway,England,1.0,2.0,FIFA World Cup,Miami Gardens,United States,True
34544,2026-07-11,Argentina,Switzerland,3.0,1.0,FIFA World Cup,Kansas City,United States,True
34545,2026-07-14,France,Spain,0.0,2.0,FIFA World Cup,Arlington,United States,True
34546,2026-07-15,England,Argentina,1.0,2.0,FIFA World Cup,Atlanta,United States,True
34547,2026-07-18,France,England,4.0,6.0,FIFA World Cup,Miami Gardens,United States,True
34548,2026-07-19,Spain,Argentina,1.0,0.0,FIFA World Cup,East Rutherford,United States,True

In [5]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34549 entries, 0 to 34548
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        34549 non-null  object
 1   home_team   34549 non-null  object
 2   away_team   34549 non-null  object
 3   home_score  34549 non-null  float64
 4   away_score  34549 non-null  float64
 5   tournament  34549 non-null  object
 6   city        34549 non-null  object
 7   country     34549 non-null  object
 8   neutral     34549 non-null  bool
dtypes: bool(1), float64(2), object(6)
memory usage: 2.1+ MB

In [6]:
matches["date"] = pd.to_datetime(matches["date"])

In [7]:
matches["tournament"].value_counts()

tournament
Friendly                                16631
FIFA World Cup qualification             8328
UEFA Euro qualification                  2567
African Cup of Nations qualification     2215
FIFA World Cup                           1000
Copa América                              869
African Cup of Nations                    828
AFC Asian Cup qualification               790
AFC Asian Cup                             413
Gold Cup                                  373
UEFA Euro                                 370
Oceania Nations Cup                        83
Gold Cup qualification                     54
Oceania Nations Cup qualification          20
Copa América qualification                  8
Name: count, dtype: int64

In [8]:
elo.head(5)

,Unnamed: 0,date,team_a,team_b,team_a_score,team_b_score,tournament,team_a_rating,team_b_rating,team_a_rank,team_b_rank
0,0,1941-08-24,AF,IR,1,0,IND,929,1571,96.0,45.0
1,1,1948-06-03,IN,AF,4,0,F,1658,929,32.0,106.0
2,2,1948-07-26,LU,AF,6,0,OG,1307,915,84.0,107.0
3,3,1949-10-26,IR,AF,4,0,F,1571,915,44.0,112.0
4,4,1951-03-07,IN,AF,3,0,ASG,1669,914,29.0,114.0

In [80]:
elo = elo.sort_values(by = "date", ascending = False)

In [10]:
elo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51397 entries, 0 to 51396
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     51397 non-null  int64
 1   date           51397 non-null  object
 2   team_a         51397 non-null  object
 3   team_b         51397 non-null  object
 4   team_a_score   51397 non-null  int64
 5   team_b_score   51397 non-null  int64
 6   tournament     51397 non-null  object
 7   team_a_rating  51397 non-null  int64
 8   team_b_rating  51397 non-null  int64
 9   team_a_rank    51397 non-null  float64
 10  team_b_rank    51397 non-null  float64
dtypes: float64(2), int64(5), object(4)
memory usage: 4.3+ MB

In [86]:
team_ab = elo[elo["team_a"] == "US"]

In [83]:
team_ab1 = elo[elo["team_b"] == "US"]

In [82]:
team_ab.head(10)

,date,team_a,team_b,team_a_score,team_b_score,tournament,team_a_rating,team_b_rating,team_a_rank,team_b_rank
8143,2026-07-06,US,BE,1,4,WC,1747,1961,31.0,10.0
9622,2026-07-01,US,BA,2,0,WC,1798,1605,26.0,63.0
50921,2026-06-25,US,TR,2,3,WC,1781,1852,26.0,20.0
4524,2026-06-19,US,AU,2,0,WC,1820,1799,23.0,26.0
45567,2026-06-12,US,PY,4,1,WC,1780,1780,26.0,26.0
27392,2026-06-06,US,DE,1,2,F,1726,1932,38.0,10.0
48447,2026-05-31,US,SN,3,2,F,1733,1867,36.0,18.0
46406,2026-03-31,US,PT,0,2,F,1721,1984,41.0,5.0
8135,2026-03-28,US,BE,2,5,F,1730,1867,40.0,19.0
51154,2025-11-18,US,UY,5,1,F,1747,1890,34.0,14.0

In [85]:
team_ab1.head(10)

,date,team_a,team_b,team_a_score,team_b_score,tournament,team_a_rating,team_b_rating,team_a_rank,team_b_rank
35386,2024-11-14,JM,US,0,1,CNL,1586,1747,65.0,34.0
41626,2024-10-15,MX,US,2,0,F,1801,1728,23.0,40.0
50809,2023-11-20,TT,US,2,1,CLA,1432,1774,98.0,28.0
28589,2023-03-24,GD,US,1,7,CLA,1109,1808,174.0,24.0
43059,2022-12-03,NL,US,3,1,WC,2068,1817,3.0,24.0
23330,2022-11-25,EN,US,0,0,WC,1943,1808,10.0,24.0
48066,2022-09-27,SA,US,0,0,F,1633,1796,55.0,25.0
35880,2022-09-23,JP,US,2,0,F,1798,1801,27.0,26.0
22396,2022-06-14,SV,US,1,1,CLA,1501,1818,80.0,24.0
17150,2022-03-30,CR,US,2,0,WQ,1742,1820,33.0,23.0

In [11]:
elo = elo.drop(columns=["Unnamed: 0"])

In [12]:
elo["date"] = pd.to_datetime(elo["date"])

In [13]:
elo["tournament"].value_counts()

tournament
F      17184
WQ      7851
EQ      2824
FQ      2345
WC      1068
       ...
EGM        1
RJC        1
CFA        1
UAC        1
PNF        1
Name: count, Length: 489, dtype: int64

In [14]:
filename = "../data/external/en.tournaments.tsv" 
delimiter = "\t"

with open(filename, "r") as f: 
    reader = csv.reader(f, delimiter=delimiter) 
    data = [row[:2] for row in reader if row] 
    

tourney_df = pd.DataFrame(data, columns=["tourney_code", "tourney_name"])

In [15]:
tourney_df.head(5)

  tourney_code                 tourney_name
0           WC                    World Cup
1           OG                Olympic Games
2           EC        European Championship
3           CA                 Copa America
4           SA  South American Championship

In [16]:
elo_tourney = pd.merge(elo, tourney_df, left_on="tournament", right_on = "tourney_code", how = "left")

elo_tourney.head(5)

,date,team_a,team_b,team_a_score,team_b_score,tournament,team_a_rating,team_b_rating,team_a_rank,team_b_rank,tourney_code,tourney_name
0,1941-08-24,AF,IR,1,0,IND,929,1571,96.0,45.0,IND,Independence Tournament
1,1948-06-03,IN,AF,4,0,F,1658,929,32.0,106.0,F,Friendly
2,1948-07-26,LU,AF,6,0,OG,1307,915,84.0,107.0,OG,Olympic Games
3,1949-10-26,IR,AF,4,0,F,1571,915,44.0,112.0,F,Friendly
4,1951-03-07,IN,AF,3,0,ASG,1669,914,29.0,114.0,ASG,Asian Games

In [17]:
elo_tourney["tourney_name"].unique()

array(['Independence Tournament', 'Friendly', 'Olympic Games',
       'Asian Games', 'Olympic Games qualifier', 'Asian Cup qualifier',
       'Republic Day Cup', 'Great Leader Cup', 'South Asian Championship',
       'World Cup qualifier', 'Friendship Cup', 'Asian Challenge Cup',
       'Asian Cup and Asian Challenge Cup qualifier',
       'Asian Cup qualifier and Asian Challenge Cup',
       'World Cup and Asian Cup qualifier', 'Airmarine Cup',
       'Central Asian Nations Cup', 'Friendly tournament',
       'Diamond Jubilee Tournament', 'Balkan Cup',
       'Balkan and Central European Championship',
       'European Championship qualifier', "Prime Minister's Cup",
       'European Championship', 'European Nations League C',
       'European Nations League B', 'Djamila Bouhired Tournament',
       'African Games qualifier', 'African Games',
       'African Nations Cup qualifier', 'Mediterranean Games',
       'African Nations Cup', 'November 1st Cup',
       'Evacuation Day Tournament', 'Palestine Cup', 'Kuneitra Cup',
       'North African Cup', 'Tripoli International Fair Tournament',
       'World Cup', 'Friendship Tournament', 'Pan-Arab Games',
       'Independence Cup', 'Arab Cup qualifier', 'Arab Cup',
       'Friendship Challenge', 'Afro-Asian Cup', 'November 7th Cup',
       'African Ram Tournament',
       'World Cup and African Nations Cup qualifier', 'FIFA Series',
       'Almada Cup', 'European Nations League D', 'Zone V Tournament',
       'Central African Games',
       'African Games qualifier and Central African Games',
       'SADCC Tournament', 'COSAFA Cup',
       'Caribbean Championship qualifier',
       'CONCACAF Championship and Caribbean Cup qualifier',
       'Caribbean Cup qualifier',
       'CONCACAF Championship and Caribbean Championship qualifier',
       'CONCACAF Nations League qualifier', 'CONCACAF Nations League C',
       'Pelican Cup', 'CONCACAF Series', 'Leeward Islands Tournament',
       'World Cup and CONCACAF Championship qualifier',
       'Caribbean Championship', 'Central American and Caribbean Games',
       'OECS Championship', 'Caribbean Cup',
       'CONCACAF Championship qualifier and Caribbean Cup',
       'Western Union Championship', 'CONCACAF Championship qualifier',
       'Challenge Cup',
       'CONCACAF Championship qualifier and Caribbean Championship',
       'Parbo Beer Cup', "President's Cup Challenge",
       'CONCACAF Nations League B', 'Lipton Cup', 'Newton Cup',
       'Argentinian Honor Award Cup', 'May Revolution Centennial Cup',
       'Uruguayan Honor Award Cup', 'Montevideo Cup', 'Saenz Pena Cup',
       'President Roque Saenz Peña Cup', 'Press Circle Cup',
       'Julio Argentino Roca Cup', 'South American Championship',
       'Roberto Chery Cup', 'La Plata Cup', 'Rosa Chevallier Boutell Cup',
       'Foreign Minister Cup', 'Confraternity Cup',
       'La Plata River Confraternity Cup', 'Buenos Aires Cup',
       'Argentine Chamber of Deputies Cup',
       'Uruguayan Automotive Center Cup', 'Hector Gomez Cup',
       'Juan Mignaburu Cup', "Chile President's Cup",
       "Argentina President's Cup", 'Panamerican Championship',
       'Atlantic Cup', 'Raul Colombo Cup', 'Carlos Dittborn Cup',
       'Cup of Nations', 'Hispanic Heritage Cup', 'Ramon Castilla Cup',
       'Cornelio Saavedra Cup', 'Copa America', 'Mexico City Cup',
       'Atlantic Cup and Felix Bogado Cup',
       'Atlantic Cup and Julio Roca Cup', 'Atlantic Cup and Lipton Cup',
       'Atlantic Cup and Newton Cup', 'Felix Bogado Cup',
       'World Champions Gold Cup', 'Nehru Gold Cup',
       'Bicentenary Gold Cup', 'Kirin Cup',
       'Intercontinental Championship', 'AFA Centenary Cup',
       'Artemio Franchi Trophy', 'Salta Cup',
       'Nelson Mandela Challenge Cup', 'Cordoba Municipality Cup',
       'Buenos Aires Province Cup', 'Clarin 50th Anniversary Cup',
       'Reebok Cup', 'Zero Hora 35th Anniversary Cup',
       'Confederations Cup', 'Buenos Aires Province Lottery Cup',
       'Chaco Cup', 'Times of India Cup', 'Nicolas Leoz Cup',
       'Francisco Cup', 'Adidas Cup', 'Albena-Mobitel Tournament',
       'European Nations League B/C Play-off', 'Harold Oduber Cup',
       'WICO Challenge Cup', 'Governor Brons Trophy', 'CCCF Championship',
       'ABC Tournament', 'ABCS Tournament', 'Soccer Ashes Trophy',
       'South Vietnam National Day Tournament', 'Oceania Nations Cup',
       'Merlion Cup', 'Trans-Tasman Cup', 'Ampol Cup', "President's Cup",
       'Oceania Nations Cup and Trans-Tasman Cup', 'Simba Cup',
       'Optus World Series', 'Valparaiso City Cup',
       'AFC-OFC Challenge Cup',
       'World Cup qualifier and Oceania Nations Cup', 'Asian Cup',
       'East Asian Championship qualifier', 'East Asian Championship',
       'Wagner Trophy', 'European International Cup',
       'Continents Tournament', 'European Nations League A',
       'European Nations League A/B Play-off', 'ECO Cup',
       'San Pellegrino Tournament', 'Alma TV Cup', 'International Cup',
       'Panamerican Games', 'Panamerican Games qualifier', 'Gulf Cup',
       'Great Artificial River Tournament', 'West Asian Games',
       'West Asian Championship', "King's Cup", "President's Gold Cup",
       'South Asian Games', 'Nepal Panchayat Silver Jubilee Cup',
       'Golden Jubilee Cup', 'Millenium Cup',
       "Jigme Wangchuk Memorial King's Cup", 'Grand Royal Challenge Cup',
       'Bangabandhu Gold Cup', "Prime Minister's Trophy",
       'Martinez Shield', 'Friendship Trophy', 'Daily Nation Trophy',
       'Windward Islands Tournament', 'Dudley Eve Memorial Trophy',
       'Courts Caribbean Classic', 'LG Cup', 'Evence Coppee Trophy',
       'Van den Abeele Cup', 'Rotterdamsch Nieuwsblad Cup',
       'Laveleye Cup', 'King Hassan Tournament',
       'European Nations League',
       'CONCACAF Championship qualifier and UNCAF Nations Cup',
       'CONCACAF Championship and UNCAF Nations Cup qualifier',
       'CONCACAF Championship qualifier and Central American Cup',
       'Central American Cup', 'CONCACAF Championship', 'Nkrumah Cup',
       'French Commonwealth Games', 'Friendship Games',
       'West African Nations Cup', 'CEDEAO Cup qualifier',
       'Solidarity Tournament', 'Amilcar Cabral Cup', 'TIFOCO Tournament',
       'Island Games', 'CONCACAF Nations League A',
       "Sikkim Governor's Gold Cup", 'Bolivarian Games',
       'Chaco Peace Cup', 'Marshal Sucre Cup', 'Provoste Cup',
       'Joe Robbie Cup', 'US Cup', 'Peace Cup', 'Dunhill Cup',
       'Blair Trophy', "King's Millenium Cup", 'Mukuru Tournament',
       'Rodrigues Alves Cup', 'Rio Branco Cup', 'Oswaldo Cruz Cup',
       "Bernardo O'Higgins Cup", 'Jorge Chavez-Santos Dumont Cup',
       'Emilio Garrastazu Medici Cup', 'Atlantic Cup and Rio Branco Cup',
       'Atlantic Cup and Oswaldo Cruz Cup', 'Bicentennial Cup',
       'Stanley Rous Cup', 'Teixeira Cup', 'Umbro Cup', 'Carlsberg Cup',
       'Southeast Asian Games', 'Independence Games',
       'Southeast Asian Championship',
       'Southeast Asian Championship qualifier', 'Asian Solidarity Cup',
       'Nations Cup', 'CEDEAO Cup', 'Francophone Games',
       'ECOWAS Tournament', 'Black Stars Tournament', 'Gabon Radio Cup',
       'West African Nations Cup qualifier', 'Afro-Asian Games',
       'Unity Cup', 'ECGLC Tournament', 'CECAFA Cup',
       'Nile Basin Tournament', 'Southeast Asian Peninsula Games',
       'GANEFO Tournament', 'Jakarta Anniversary Tournament',
       'Tropical Cup', 'African Games qualifier and Central African Cup',
       'UDEAC Cup', 'World Cup qualifier and CONCACAF Championship',
       'Miami Cup', 'Stanley Matthews Cup', 'North American Championship',
       'Columbus Cup', 'Skydome Cup', 'Canada Cup', 'Caribana Cup',
       'CONCACAF Nations League', 'Copa America qualifier',
       'Canadian Shield', 'Western Union Super Cup', 'UNIFAC Cup',
       'CEMAC Cup', 'Pacific Cup', 'Juan Pinto Duran Cup',
       'South American Championship qualifier', 'Boqueron Cup',
       'Centenary Cup', 'China Cup', 'Far Eastern Games',
       'Open International Championship', 'Lunar New Year Cup',
       'Great Wall Cup', 'Dynasty Cup', 'Ancient Civilizations Cup',
       'Philips Cup', 'Dubai Challenge', 'Financing City Cup',
       'Gonzalo Jimenez de Quesada Cup', 'Budweiser Cup',
       'Elisabethville Trade Fair', 'Saba Saba Festival Tournament',
       'Indian Ocean Tournament', 'South Pacific Games',
       'Oceania Nations Cup qualifier and Polynesian Cup',
       'World Cup and Oceania Nations Cup qualifier',
       'World Cup and Oceania Nations Cup qualifier and South Pacific Games',
       'Oceania Nations Cup qualifier and South Pacific Games',
       'Pacific Games', 'Oceania Nations Cup qualifier',
       'Central American Independence Centennial Games',
       'Central American Games', 'Juan Santamaria Cup', 'Revolution Cup',
       'Korea Cup', 'UNCAF Nations Cup',
       'Central American Independence Cup', 'Antel Cup',
       'Al-Nashama Tournament', 'Marjan Trophy',
       'FIFA Series and Capital Cup',
       'World Cup qualifier and North American Championship',
       'Barquisimeto City Cup', 'Ricardo Morales Aviles Cup',
       'Governor van Slobbe Cup', 'Dennert Cup',
       'Governor Brons Trophy and Governor van Slobbe Cup',
       'Heineken Cup', 'Phillip Seaga Cup', 'Duvalier Cup',
       'Inter Expo Cup', 'Chippie Polar Cup', 'Slavic Tournament',
       'Eduard Benes Cup',
       'Balkan and Central European Championship and European International Cup',
       'Mohammed V Cup', 'Pier Cesare Baretti Memorial',
       'Revolution Anniversary Tournament', 'Castle Lager Cup',
       'Nordic Championship',
       'Olympic Games qualifier and Nordic Championship',
       'Scania 100 Tournament',
       'World Cup qualifier and Nordic Championship',
       'Goodwill Tournament', 'Bruno Garisto Cup',
       'Mediterranean Friendship Cup', 'East Mediterranean Cup',
       'Mediterranean Cup', 'Pan-Arab Games and Arab Cup', 'Cairo Cup',
       'Hurricane Relief Tournament', 'Coliseum Cup', 'Delta Cup',
       'British Championship',
       'World Cup qualifier and British Championship',
       'European Championship qualifier and British Championship',
       'William Poole Cup', 'Mexico City Cup and Azteca 2000 Tournament',
       'Azteca 2000 Tournament', 'COMESA Cup', 'Baltic Cup',
       'Turaani Tournament', 'Baltic Tournament', 'Ho Chi Minh City Cup',
       "Mayors' Cup", 'BSE 100th Anniversary Cup', 'Rotary Cup',
       'Toyota Challenge Cup', 'East African Friendship Cup',
       'South Pacific Mini-Games', 'Melanesian Cup',
       'Oceania Nations Cup qualifier and Melanesian Cup',
       'Pacific Mini-Games', 'Lahti Cup', 'Corsica Cup',
       'African Games qualifier and West African Cup',
       'West African Cup and Amilcar Cabral Cup', 'West African Cup',
       'Peace Trophy', 'Centenary Tournament', 'Jalco Cup', 'Akwei Cup',
       'Azikiwe Cup', 'Freedom Cup', 'Asics Cup', 'Panafest Trophy',
       'Mini World Cup', 'European Nations League C/D Play-off',
       'Micronesian Games',
       'East Asian Championship qualifier and Marianas Cup',
       'Marianas Cup', 'Montreal Cup', 'Peter Stuyvesant Trophy',
       'Balewa Trophy', 'Siaka Stevens Cup', 'Samuel K Doe Cup',
       'Peace and Friendship Tournament', 'Walcott Cup',
       'Amo Amateur Cup', 'Brown Betty Cup', 'Heineken Trophy',
       'President Paul Magloire Cup', 'Frantz Fanon Tournament',
       'Digicel Shield',
       'CONCACAF Championship qualifier and Caribbean Championship playoff',
       'Robert Jobez Cup', 'Aw Hoe Memorial Cup',
       'Tiger Football Festival', 'Long Teng Cup', 'AYA Bank Cup',
       'Danube Cup', 'Greenland Cup', 'Colombo Cup', 'Marah Halim Cup',
       'Intercontinental Cup', 'Vietnam FF Cup', 'Tiger Challenge',
       'Al Nakba Cup', 'Garuda Championship Series',
       'RCD Pact Tournament', 'Valeri Lobanovsky Memorial',
       'Republic Bank Cup', 'Andre Kamperveen Memorial Trophy',
       'Basdeo Panday Trophy', 'East Asia Games', 'Adidas Challenge',
       'Central Asian Cup', 'Gossage Cup', 'Triangulaire',
       'Jomo Kenyatta Cup',
       'East and Central African Senior Challenge Cup',
       'Saudi Arabia FF Tournament', 'Indian Ocean Cup',
       'Anniversary Cup', 'Genocide Commemoration Cup', 'Navruz Cup',
       'World Cup qualifier and Baltic Cup',
       'Mano River Union Tournament', 'Islamic Games', 'Libyana Cup',
       'Benghazi Invitational Cup', 'Indian Ocean Games',
       'Armed Forces Day Tournament', "Sportsman's Trophy",
       'Ovaltine Cup', 'Causeway Cup', 'Causeway Challenge Cup',
       'Bristol Freedom Cup', 'South Asian Super Cup', 'Carta Blanca Cup',
       'Moctezuma Cup', 'Castillo Najera Cup', 'Guadalajara City Cup',
       'Camel Cup', 'Confederations Cup qualifier and CONCACAF Cup',
       'East Asian Games', 'Kam Wo Trophy', 'ANFA Cup',
       'South Pacific Cup', 'French Territory Cup',
       'Tiger Bay Challenge Trophy', 'Saudi Arabia FF Cup',
       'Millennium Cup',
       'European Championship qualifier and Nordic Championship',
       'Bossio Cup', 'Trompowski Cup', 'Artigas Cup',
       'Atlantic Cup and Artigas Cup', 'MUFP Cup', 'Parra del Riego Cup',
       'El Inca Cup', 'Inter-Port Friendship Cup', 'King Piotr II Cup',
       'King Alexander Cup', 'King Carol Cup',
       'Danube Cup and King Mihai Cup', 'Prudent Cup',
       'Reunification Cup', 'Mikasa Challenge Cup', 'Wantok Cup',
       'Outrigger Challenger Cup', 'Heroes Cup', 'Polar Beer Cup',
       'Sheikh Rashid bin Mohammed Ramadan Championship', 'Levy Cup',
       'Rhodes Centenary Trophy', 'Currie Cup'], dtype=object)

In [18]:
world_cup_keywords = [
    "World Cup",
]

possible_matches = elo_tourney[elo_tourney["tourney_name"].str.contains("|".join(world_cup_keywords), case = False, na=False)]["tourney_name"].drop_duplicates().sort_values()


valid = [
    "World Cup", #World Cup
    "World Cup qualifier",
    "World Cup and African Nations Cup qualifier",
    "World Cup and Asian Cup qualifier",
    "World Cup and CONCACAF Championship qualifier",
    "World Cup and Oceania Nations Cup qualifier and South Pacific Games",
    "World Cup qualifier and Baltic Cup",
    "World Cup qualifier and British Championship",
    "World Cup qualifier and CONCACAF Championship",
    "World Cup qualifier and Nordic Championship",
    "World Cup qualifier and North American Championship",
    "World Cup qualifier and Oceania Nations Cup",
    "World Cup and Oceania Nations Cup qualifier",
    "European Championship", #Euros
    "European Championship qualifier", 
    "European Championship qualifier and British Championship",
    "European Championship qualifier and Nordic Championship",
    "Copa America", #Copa America
    "Copa America qualifier",
    "African Nations Cup", #AFCON
    "African Nations Cup qualifier",
    "Asian Cup", #Asian Cup
    "Asian Cup qualifier",
    "Asian Cup and Asian Challenge Cup qualifier",
    "Asian Cup qualifier and Asian Challenge Cup",
    "CONCACAF Championship", #Gold Cup
    "CONCACAF Championship and Caribbean Championship qualifier",
    "CONCACAF Championship and Caribbean Cup qualifier",
    "CONCACAF Championship and UNCAF Nations Cup qualifier",
    "CONCACAF Championship qualifier",
    "CONCACAF Championship qualifier and Caribbean Championship",
    "CONCACAF Championship qualifier and Caribbean Championship playoff",
    "CONCACAF Championship qualifier and Caribbean Cup",
    "CONCACAF Championship qualifier and Central American Cup",
    "CONCACAF Championship qualifier and UNCAF Nations Cup",
    "Oceania Nations Cup", #Oceania
    "Oceania Nations Cup and Trans-Tasman Cup",
    "Oceania Nations Cup qualifier",
    "Oceania Nations Cup qualifier and Melanesian Cup",
    "Oceania Nations Cup qualifier and Polynesian Cup",
    "Oceania Nations Cup qualifier and South Pacific Games",
    "Friendly" #friendlies 
    
]


map_tournaments = {
    "World Cup": "FIFA World Cup",
    "World Cup qualifier": "FIFA World Cup qualification",
    "World Cup and African Nations Cup qualifier": "FIFA World Cup qualification",
    "World Cup and Asian Cup qualifier": "FIFA World Cup qualification",
    "World Cup and CONCACAF Championship qualifier": "FIFA World Cup qualification",
    "World Cup and Oceania Nations Cup qualifier and South Pacific Games": "FIFA World Cup qualification",
    "World Cup qualifier and Baltic Cup": "FIFA World Cup qualification",
    "World Cup qualifier and British Championship": "FIFA World Cup qualification",
    "World Cup qualifier and CONCACAF Championship": "FIFA World Cup qualification",
    "World Cup qualifier and Nordic Championship": "FIFA World Cup qualification",
    "World Cup qualifier and North American Championship": "FIFA World Cup qualification",
    "World Cup qualifier and Oceania Nations Cup": "FIFA World Cup qualification",
    "World Cup and Oceania Nations Cup qualifier": "FIFA World Cup qualification",
    "European Championship": "UEFA Euro",
    "European Championship qualifier": "UEFA Euro qualification",
    "European Championship qualifier and British Championship": "UEFA Euro qualification",
    "European Championship qualifier and Nordic Championship": "UEFA Euro qualification",
    "Copa America": "Copa América",
    "Copa America qualifier": "Copa América qualification",
    "African Nations Cup": "African Cup of Nations", #AFCON
    "African Nations Cup qualifier": "African Cup of Nations qualification",
    "Asian Cup": "AFC Asian Cup",
    "Asian Cup qualifier": "AFC Asian Cup qualification",
    "Asian Cup and Asian Challenge Cup qualifier": "AFC Asian Cup qualification",
    "Asian Cup qualifier and Asian Challenge Cup": "AFC Asian Cup qualification",
    "CONCACAF Championship": "Gold Cup",
    "CONCACAF Championship and Caribbean Championship qualifier": "Gold Cup qualification",
    "CONCACAF Championship and Caribbean Cup qualifier": "Gold Cup qualification",
    "CONCACAF Championship and UNCAF Nations Cup qualifier": "Gold Cup qualification",
    "CONCACAF Championship qualifier": "Gold Cup qualification",
    "CONCACAF Championship qualifier and Caribbean Championship": "Gold Cup qualification",
    "CONCACAF Championship qualifier and Caribbean Championship playoff": "Gold Cup qualification",
    "CONCACAF Championship qualifier and Caribbean Cup": "Gold Cup qualification",
    "CONCACAF Championship qualifier and Central American Cup": "Gold Cup qualification",
    "CONCACAF Championship qualifier and UNCAF Nations Cup": "Gold Cup qualification",
    "Oceania Nations Cup": "Oceania Nations Cup",
    "Oceania Nations Cup and Trans-Tasman Cup": "Oceania Nations Cup qualification",
    "Oceania Nations Cup qualifier": "Oceania Nations Cup qualification",
    "Oceania Nations Cup qualifier and Melanesian Cup": "Oceania Nations Cup qualification",
    "Oceania Nations Cup qualifier and Polynesian Cup": "Oceania Nations Cup qualification",
    "Oceania Nations Cup qualifier and South Pacific Games": "Oceania Nations Cup qualification",
    "Friendly": "Friendly"
}
possible_matches

27947                                       Mini World Cup
754                                              World Cup
1005           World Cup and African Nations Cup qualifier
93                       World Cup and Asian Cup qualifier
2048         World Cup and CONCACAF Championship qualifier
16485          World Cup and Oceania Nations Cup qualifier
16489    World Cup and Oceania Nations Cup qualifier an...
34                                     World Cup qualifier
37806                   World Cup qualifier and Baltic Cup
22725         World Cup qualifier and British Championship
13346        World Cup qualifier and CONCACAF Championship
20275          World Cup qualifier and Nordic Championship
17555    World Cup qualifier and North American Champio...
4279           World Cup qualifier and Oceania Nations Cup
Name: tourney_name, dtype: object

In [19]:
elo_tourney.head(5)

,date,team_a,team_b,team_a_score,team_b_score,tournament,team_a_rating,team_b_rating,team_a_rank,team_b_rank,tourney_code,tourney_name
0,1941-08-24,AF,IR,1,0,IND,929,1571,96.0,45.0,IND,Independence Tournament
1,1948-06-03,IN,AF,4,0,F,1658,929,32.0,106.0,F,Friendly
2,1948-07-26,LU,AF,6,0,OG,1307,915,84.0,107.0,OG,Olympic Games
3,1949-10-26,IR,AF,4,0,F,1571,915,44.0,112.0,F,Friendly
4,1951-03-07,IN,AF,3,0,ASG,1669,914,29.0,114.0,ASG,Asian Games

In [20]:
filtered_arg = elo_tourney[
    ((elo_tourney["team_b"] == "AR") | (elo_tourney["team_a"] == "AR")) & 
    (elo_tourney["tourney_name"] == "World Cup") &
    (elo_tourney["date"] >= "2026-06-22")
]

filtered_arg

,date,team_a,team_b,team_a_score,team_b_score,tournament,team_a_rating,team_b_rating,team_a_rank,team_b_rank,tourney_code,tourney_name
3433,2026-06-22,AR,AT,2,0,WC,2144,1841,1.0,21.0,WC,World Cup
3434,2026-06-27,AR,JO,3,1,WC,2148,1628,1.0,57.0,WC,World Cup
3435,2026-07-03,AR,CV,3,2,WC,2151,1619,2.0,59.0,WC,World Cup
3436,2026-07-07,AR,EG,3,2,WC,2156,1742,2.0,34.0,WC,World Cup
3437,2026-07-11,AR,CH,3,1,WC,2177,1928,2.0,11.0,WC,World Cup
3438,2026-07-15,AR,EN,2,1,WC,2200,2074,2.0,4.0,WC,World Cup
3439,2026-07-19,ES,AR,1,0,WC,2259,2173,1.0,2.0,WC,World Cup

In [21]:
matches_arg = matches[
    ((matches["away_team"] == "Argentina") | (matches["home_team"] == "Argentina")) & 
    (matches["tournament"] == "FIFA World Cup") & 
    (matches["date"] >= "2026-06-22")
]
matches_arg

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
34487,2026-06-22,Argentina,Austria,2.0,0.0,FIFA World Cup,Arlington,United States,True
34512,2026-06-27,Jordan,Argentina,1.0,3.0,FIFA World Cup,Arlington,United States,True
34531,2026-07-03,Argentina,Cape Verde,3.0,2.0,FIFA World Cup,Miami Gardens,United States,True
34539,2026-07-07,Argentina,Egypt,3.0,2.0,FIFA World Cup,Atlanta,United States,True
34544,2026-07-11,Argentina,Switzerland,3.0,1.0,FIFA World Cup,Kansas City,United States,True
34546,2026-07-15,England,Argentina,1.0,2.0,FIFA World Cup,Atlanta,United States,True
34548,2026-07-19,Spain,Argentina,1.0,0.0,FIFA World Cup,East Rutherford,United States,True

In [22]:
elo_tourney["tournament_bucket"] = elo_tourney["tourney_name"].map(map_tournaments)

In [23]:
elo_tourney.head(5)

,date,team_a,team_b,team_a_score,team_b_score,tournament,team_a_rating,team_b_rating,team_a_rank,team_b_rank,tourney_code,tourney_name,tournament_bucket
0,1941-08-24,AF,IR,1,0,IND,929,1571,96.0,45.0,IND,Independence Tournament,NaN
1,1948-06-03,IN,AF,4,0,F,1658,929,32.0,106.0,F,Friendly,Friendly
2,1948-07-26,LU,AF,6,0,OG,1307,915,84.0,107.0,OG,Olympic Games,NaN
3,1949-10-26,IR,AF,4,0,F,1571,915,44.0,112.0,F,Friendly,Friendly
4,1951-03-07,IN,AF,3,0,ASG,1669,914,29.0,114.0,ASG,Asian Games,NaN

In [24]:
elo_tourney["tournament_bucket"].value_counts()

tournament_bucket
Friendly                                17184
FIFA World Cup qualification             9015
UEFA Euro qualification                  2837
African Cup of Nations qualification     2345
FIFA World Cup                           1068
AFC Asian Cup qualification              1067
Gold Cup qualification                    926
African Cup of Nations                    833
Gold Cup                                  502
Copa América                              491
AFC Asian Cup                             421
UEFA Euro                                 388
Oceania Nations Cup                        86
Oceania Nations Cup qualification          70
Copa América qualification                  4
Name: count, dtype: int64

In [25]:
copa_qual = elo_tourney[elo_tourney["tournament_bucket"] == "Copa América qualification"]
copa_qual

,date,team_a,team_b,team_a_score,team_b_score,tournament,team_a_rating,team_b_rating,team_a_rank,team_b_rank,tourney_code,tourney_name,tournament_bucket
13714,2024-03-23,CA,TT,2,0,CAQ,1715,1417,38.0,101.0,CAQ,Copa America qualifier,Copa América qualification
17178,2024-03-23,CR,HN,3,1,CAQ,1605,1490,62.0,85.0,CAQ,Copa America qualifier,Copa América qualification
17855,2016-01-08,PA,CU,4,0,CAQ,1687,1334,42.0,123.0,CAQ,Copa America qualifier,Copa América qualification
30141,2016-01-08,HT,TT,1,0,CAQ,1503,1586,87.0,61.0,CAQ,Copa America qualifier,Copa América qualification

In [26]:
elo_tourney = elo_tourney.dropna(subset=["tournament_bucket"])
elo_tourney = elo_tourney.reset_index(drop = True)

In [27]:
elo_tourney.tail(20)

,date,team_a,team_b,team_a_score,team_b_score,tournament,team_a_rating,team_b_rating,team_a_rank,team_b_rank,tourney_code,tourney_name,tournament_bucket
37217,2005-12-31,ZW,ZM,1,1,F,1502,1526,82.0,75.0,F,Friendly,Friendly
37218,2006-07-15,ZM,ZW,0,0,F,1503,1501,80.0,81.0,F,Friendly,Friendly
37219,2010-09-05,ZM,KM,4,0,FQ,1559,867,74.0,203.0,FQ,African Nations Cup qualifier,African Cup of Nations qualification
37220,2011-08-10,ZW,ZM,2,0,F,1372,1531,114.0,79.0,F,Friendly,Friendly
37221,2011-09-04,KM,ZM,1,2,FQ,883,1533,203.0,77.0,FQ,African Nations Cup qualifier,African Cup of Nations qualification
37222,2012-08-08,ZM,ZW,2,1,F,1607,1347,59.0,118.0,F,Friendly,Friendly
37223,2013-04-28,ZM,ZW,2,0,F,1546,1360,71.0,119.0,F,Friendly,Friendly
37224,2016-11-05,ZW,ZM,1,0,F,1398,1411,109.0,105.0,F,Friendly,Friendly
37225,2017-03-26,ZW,ZM,0,0,F,1400,1442,107.0,95.0,F,Friendly,Friendly
37226,2019-11-19,ZM,ZW,1,2,FQ,1432,1408,97.0,104.0,FQ,African Nations Cup qualifier,African Cup of Nations qualification
37227,2021-03-29,ZW,ZM,0,2,FQ,1400,1493,102.0,80.0,FQ,African Nations Cup qualifier,African Cup of Nations qualification
37228,2021-09-03,MR,ZM,1,2,WQ,1374,1471,109.0,86.0,WQ,World Cup qualifier,FIFA World Cup qualification
37229,2021-11-13,ZM,MR,4,0,WQ,1433,1341,93.0,117.0,WQ,World Cup qualifier,FIFA World Cup qualification
37230,2022-06-07,ZM,KM,2,1,FQ,1421,1285,99.0,136.0,FQ,African Nations Cup qualifier,African Cup of Nations qualification
37231,2023-09-09,KM,ZM,1,1,FQ,1194,1510,161.0,78.0,FQ,African Nations Cup qualifier,African Cup of Nations qualification
37232,2025-12-26,KM,ZM,0,0,AR,1358,1374,114.0,109.0,AR,African Nations Cup,African Cup of Nations
37233,1982-07-18,ZW,RE,1,1,F,1495,1115,69.0,150.0,F,Friendly,Friendly
37234,1982-07-25,ZW,RE,2,3,F,1476,1134,78.0,146.0,F,Friendly,Friendly
37235,2003-10-12,ZW,MR,3,0,WQA,1526,1106,71.0,169.0,WQA,World Cup and African Nations Cup qualifier,FIFA World Cup qualification
37236,2003-11-14,MR,ZW,2,1,WQA,1140,1468,168.0,86.0,WQA,World Cup and African Nations Cup qualifier,FIFA World Cup qualification

In [28]:
elo_tourney.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37237 entries, 0 to 37236
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               37237 non-null  datetime64[ns]
 1   team_a             37237 non-null  object
 2   team_b             37237 non-null  object
 3   team_a_score       37237 non-null  int64
 4   team_b_score       37237 non-null  int64
 5   tournament         37237 non-null  object
 6   team_a_rating      37237 non-null  int64
 7   team_b_rating      37237 non-null  int64
 8   team_a_rank        37237 non-null  float64
 9   team_b_rank        37237 non-null  float64
 10  tourney_code       37237 non-null  object
 11  tourney_name       37237 non-null  object
 12  tournament_bucket  37237 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(4), object(6)
memory usage: 3.7+ MB

In [29]:
pd.set_option("display.max_colwidth", None)

In [30]:
euro_keywords = [
    "Euro",
]

possible_matches = elo_tourney[elo_tourney["tourney_name"].str.contains("|".join(euro_keywords), case = False, na=False)]["tourney_name"].drop_duplicates().sort_values()

valid = [
    "European Championship",
    "European Championship qualifier", 
    "European Championship qualifier and British Championship",
    "European Championship qualifier and Nordic Championship"
]
possible_matches

395                                         European Championship
128                               European Championship qualifier
17310    European Championship qualifier and British Championship
32545     European Championship qualifier and Nordic Championship
Name: tourney_name, dtype: object

In [31]:
copa_keywords = [
    "Copa America",
]

possible_matches = elo_tourney[elo_tourney["tourney_name"].str.contains("|".join(copa_keywords), case = False, na=False)]["tourney_name"].drop_duplicates().sort_values()

possible_matches

valid = [
    "Copa America"
    "Copa America qualifier"
]

In [32]:
afcon_keywords = [
    "African",
]

possible_matches = elo_tourney[elo_tourney["tourney_name"].str.contains("|".join(afcon_keywords), case = False, na=False)]["tourney_name"].drop_duplicates().sort_values()

possible_matches

valid = [
    "African Nations Cup",
    "African Nations Cup qualifier"
]

In [33]:
asian_keywords = [
    "Asian Cup"
]

possible_matches = elo_tourney[elo_tourney["tourney_name"].str.contains("|".join(asian_keywords), case = False, na=False)]["tourney_name"].drop_duplicates().sort_values()

possible_matches

valid = [
    "Asian Cup",
    "Asian Cup qualifier",
    "Asian Cup and Asian Challenge Cup qualifier",
    "Asian Cup qualifier and Asian Challenge Cup"
]

In [34]:
gold_keywords = [
    "CONCACAF"
]

possible_matches = elo_tourney[elo_tourney["tourney_name"].str.contains("|".join(gold_keywords), case = False, na=False)]["tourney_name"].drop_duplicates().sort_values()

possible_matches

valid = [
    "CONCACAF Championship",
    "CONCACAF Championship and Caribbean Championship qualifier",
    "CONCACAF Championship and Caribbean Cup qualifier",
    "CONCACAF Championship and UNCAF Nations Cup qualifier",
    "CONCACAF Championship qualifier",
    "CONCACAF Championship qualifier and Caribbean Championship",
    "CONCACAF Championship qualifier and Caribbean Championship playoff",
    "CONCACAF Championship qualifier and Caribbean Cup",
    "CONCACAF Championship qualifier and Central American Cup",
    "CONCACAF Championship qualifier and UNCAF Nations Cup"
]

In [35]:
oceania_keywords = [
    "Oceania"
]

possible_matches = elo_tourney[elo_tourney["tourney_name"].str.contains("|".join(oceania_keywords), case = False, na=False)]["tourney_name"].drop_duplicates().sort_values()

possible_matches

valid = [
"Oceania Nations Cup",
"Oceania Nations Cup and Trans-Tasman Cup",
"Oceania Nations Cup qualifier",
"Oceania Nations Cup qualifier and Melanesian Cup",
"Oceania Nations Cup qualifier and Polynesian Cup",
"Oceania Nations cup qualifier and South Pacific Games",
]

In [36]:
friendly_keywords = [
    "Friend"
]

possible_matches = elo_tourney[elo_tourney["tourney_name"].str.contains("|".join(friendly_keywords), case = False, na=False)]["tourney_name"].drop_duplicates().sort_values()

possible_matches

0    Friendly
Name: tourney_name, dtype: object

In [37]:
possible_matches.value_counts()

tourney_name
Friendly    1
Name: count, dtype: int64

In [38]:
possible_matches.count()

np.int64(1)

In [39]:
euro_rows = elo_tourney[
    elo_tourney["tourney_name"].str.contains(
        "European Championship",
        case = False,
        na = False
    )
]

euro_rows.duplicated(
    subset=["date", "team_a", "team_b"],
    keep=False
).sum()

np.int64(0)

In [40]:
elo_tourney[
    elo_tourney.duplicated(
        subset=["date", "team_a", "team_b", "team_a_score", "team_b_score"],
        keep = False
    )
]

Empty DataFrame
Columns: [date, team_a, team_b, team_a_score, team_b_score, tournament, team_a_rating, team_b_rating, team_a_rank, team_b_rank, tourney_code, tourney_name, tournament_bucket]
Index: []

In [41]:
elo_tourney = elo_tourney.drop_duplicates(
    subset=["date", "team_a", "team_b", "team_a_score", "team_b_score"]
)

In [42]:
filename = "../data/external/en.teams.tsv"
delimiter = "\t"

with open(filename, "r") as f:
    reader = csv.reader(f, delimiter = delimiter)
    data = [row[:2] for row in reader if row]

teams_df = pd.DataFrame(data, columns = ["country_code", "country_name"])

In [43]:
teams_df.head(5)

  country_code country_name
0           DN         Aden
1           AF  Afghanistan
2           AL      Albania
3           DZ      Algeria
4           AD      Andorra

In [44]:
map_countries = teams_df.set_index("country_code")["country_name"]

elo_tourney["team_a_country"] = elo_tourney["team_a"].map(map_countries) 
elo_tourney["team_b_country"] = elo_tourney["team_b"].map(map_countries)

In [45]:
elo_tourney.head(10)

,date,team_a,team_b,team_a_score,team_b_score,tournament,team_a_rating,team_b_rating,team_a_rank,team_b_rank,tourney_code,tourney_name,tournament_bucket,team_a_country,team_b_country
0,1948-06-03,IN,AF,4,0,F,1658,929,32.0,106.0,F,Friendly,Friendly,India,Afghanistan
1,1949-10-26,IR,AF,4,0,F,1571,915,44.0,112.0,F,Friendly,Friendly,Iran,Afghanistan
2,1975-11-21,SA,AF,2,0,SQ,1373,896,101.0,171.0,SQ,Asian Cup qualifier,AFC Asian Cup qualification,Saudi Arabia,Afghanistan
3,1975-11-23,IQ,AF,3,1,SQ,1551,895,55.0,171.0,SQ,Asian Cup qualifier,AFC Asian Cup qualification,Iraq,Afghanistan
4,1975-11-25,QA,AF,2,1,SQ,1035,882,158.0,173.0,SQ,Asian Cup qualifier,AFC Asian Cup qualification,Qatar,Afghanistan
5,1975-11-28,SA,AF,6,0,SQ,1356,877,106.0,173.0,SQ,Asian Cup qualifier,AFC Asian Cup qualification,Saudi Arabia,Afghanistan
6,1975-11-30,IQ,AF,4,0,SQ,1540,876,58.0,173.0,SQ,Asian Cup qualifier,AFC Asian Cup qualification,Iraq,Afghanistan
7,1975-12-02,AF,QA,1,1,SQ,884,1020,173.0,159.0,SQ,Asian Cup qualifier,AFC Asian Cup qualification,Afghanistan,Qatar
8,1979-03-01,BD,AF,2,2,SQ,983,917,164.0,169.0,SQ,Asian Cup qualifier,AFC Asian Cup qualification,Bangladesh,Afghanistan
9,1979-03-02,QA,AF,3,0,SQ,1119,899,145.0,173.0,SQ,Asian Cup qualifier,AFC Asian Cup qualification,Qatar,Afghanistan

In [46]:
elo_tourney["country_pair"] = elo_tourney[["team_a_country", "team_b_country"]].apply(
    lambda row: tuple(sorted(row)), axis = 1
)

elo_tourney.head(5)

,date,team_a,team_b,team_a_score,team_b_score,tournament,team_a_rating,team_b_rating,team_a_rank,team_b_rank,tourney_code,tourney_name,tournament_bucket,team_a_country,team_b_country,country_pair
0,1948-06-03,IN,AF,4,0,F,1658,929,32.0,106.0,F,Friendly,Friendly,India,Afghanistan,"(Afghanistan, India)"
1,1949-10-26,IR,AF,4,0,F,1571,915,44.0,112.0,F,Friendly,Friendly,Iran,Afghanistan,"(Afghanistan, Iran)"
2,1975-11-21,SA,AF,2,0,SQ,1373,896,101.0,171.0,SQ,Asian Cup qualifier,AFC Asian Cup qualification,Saudi Arabia,Afghanistan,"(Afghanistan, Saudi Arabia)"
3,1975-11-23,IQ,AF,3,1,SQ,1551,895,55.0,171.0,SQ,Asian Cup qualifier,AFC Asian Cup qualification,Iraq,Afghanistan,"(Afghanistan, Iraq)"
4,1975-11-25,QA,AF,2,1,SQ,1035,882,158.0,173.0,SQ,Asian Cup qualifier,AFC Asian Cup qualification,Qatar,Afghanistan,"(Afghanistan, Qatar)"

In [47]:
matches.head(10)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False
5,1876-03-25,Scotland,Wales,4.0,0.0,Friendly,Glasgow,Scotland,False
6,1877-03-03,England,Scotland,1.0,3.0,Friendly,London,England,False
7,1877-03-05,Wales,Scotland,0.0,2.0,Friendly,Wrexham,Wales,False
8,1878-03-02,Scotland,England,7.0,2.0,Friendly,Glasgow,Scotland,False
9,1878-03-23,Scotland,Wales,9.0,0.0,Friendly,Glasgow,Scotland,False

In [48]:
matches["country_pair"] = matches[["home_team", "away_team"]].apply(
    lambda row:  tuple(sorted(row)), axis = 1
)

In [49]:
matches_duplicated = matches.duplicated(subset=["date", "country_pair"]).sum()
print(matches_duplicated)

elo_duplicated = elo_tourney.duplicated(subset=["date", "country_pair"]).sum()
print(elo_duplicated)

8
5

In [50]:
matches_duplicated

np.int64(8)

In [51]:
elo_tourney["score_pair"] = elo_tourney.apply(  #we create score pair column in elo tourney dataframe, then we apply..
    lambda row: tuple( #for each row we're creating a tuple, (?)
        score for country, score in sorted([ 
            (row["team_a_country"], row["team_a_score"]), #assigning/  accessing  for each row in country and score 
            (row["team_b_country"], row["team_b_score"])
        ])
    ),
    axis=1
)

matches["score_pair"] = matches.apply(
    lambda row: tuple (
        score for country, score in sorted([
            (row["home_team"], row["home_score"]),
            (row["away_team"], row["away_score"])
        ])
    ),
    axis = 1 
)

In [52]:
elo_tourney.head(10)

,date,team_a,team_b,team_a_score,team_b_score,tournament,team_a_rating,team_b_rating,team_a_rank,team_b_rank,tourney_code,tourney_name,tournament_bucket,team_a_country,team_b_country,country_pair,score_pair
0,1948-06-03,IN,AF,4,0,F,1658,929,32.0,106.0,F,Friendly,Friendly,India,Afghanistan,"(Afghanistan, India)","(0, 4)"
1,1949-10-26,IR,AF,4,0,F,1571,915,44.0,112.0,F,Friendly,Friendly,Iran,Afghanistan,"(Afghanistan, Iran)","(0, 4)"
2,1975-11-21,SA,AF,2,0,SQ,1373,896,101.0,171.0,SQ,Asian Cup qualifier,AFC Asian Cup qualification,Saudi Arabia,Afghanistan,"(Afghanistan, Saudi Arabia)","(0, 2)"
3,1975-11-23,IQ,AF,3,1,SQ,1551,895,55.0,171.0,SQ,Asian Cup qualifier,AFC Asian Cup qualification,Iraq,Afghanistan,"(Afghanistan, Iraq)","(1, 3)"
4,1975-11-25,QA,AF,2,1,SQ,1035,882,158.0,173.0,SQ,Asian Cup qualifier,AFC Asian Cup qualification,Qatar,Afghanistan,"(Afghanistan, Qatar)","(1, 2)"
5,1975-11-28,SA,AF,6,0,SQ,1356,877,106.0,173.0,SQ,Asian Cup qualifier,AFC Asian Cup qualification,Saudi Arabia,Afghanistan,"(Afghanistan, Saudi Arabia)","(0, 6)"
6,1975-11-30,IQ,AF,4,0,SQ,1540,876,58.0,173.0,SQ,Asian Cup qualifier,AFC Asian Cup qualification,Iraq,Afghanistan,"(Afghanistan, Iraq)","(0, 4)"
7,1975-12-02,AF,QA,1,1,SQ,884,1020,173.0,159.0,SQ,Asian Cup qualifier,AFC Asian Cup qualification,Afghanistan,Qatar,"(Afghanistan, Qatar)","(1, 1)"
8,1979-03-01,BD,AF,2,2,SQ,983,917,164.0,169.0,SQ,Asian Cup qualifier,AFC Asian Cup qualification,Bangladesh,Afghanistan,"(Afghanistan, Bangladesh)","(2, 2)"
9,1979-03-02,QA,AF,3,0,SQ,1119,899,145.0,173.0,SQ,Asian Cup qualifier,AFC Asian Cup qualification,Qatar,Afghanistan,"(Afghanistan, Qatar)","(0, 3)"

In [53]:
country_mapping = {
    "Czechia": "Czech Republic",
    "Eastern Samoa": "American Samoa",
    "Sao Tome and Principe": "São Tomé and Príncipe",
    "East Timor": "Timor-Leste",
    "US Virgin Islands": "United States Virgin Islands" 
}


cols = ["team_a_country", "team_b_country"]
elo_tourney[cols] = elo_tourney[cols].replace(country_mapping)

In [54]:
comp_key = ["date", "country_pair", "score_pair"]

overlap = pd.merge(
    elo_tourney[["date", "country_pair", "score_pair"]],
    matches[["date", "country_pair", "score_pair"]],
    on = comp_key,
    how = "inner",
    indicator = True
)

anti_join_left = overlap[overlap["_merge"] == "left_only"].drop(columns=["_merge"])

anti_join_right = overlap[overlap["_merge"] == "right_only"].drop(columns=["_merge"])


anti_join_right

Empty DataFrame
Columns: [date, country_pair, score_pair]
Index: []

In [55]:
anti_join_left

Empty DataFrame
Columns: [date, country_pair, score_pair]
Index: []

In [56]:
anti_join_left

matches_set = set(np.concatenate([matches["home_team"], matches["away_team"]]))
elo_tourney_set = set(np.concatenate([elo_tourney["team_a_country"], elo_tourney["team_b_country"]]))

In [57]:
cutoff_date = pd.to_datetime("1921-04-09")
old_name = "Ireland"

elo_tourney.loc[
    (elo_tourney["team_a_country"] == old_name) &
    (elo_tourney["date"] <= cutoff_date),
    "team_a_country"
] = "Northern Ireland"

elo_tourney.loc[
    (elo_tourney["team_b_country"] == old_name) &
    (elo_tourney["date"] <= cutoff_date),
    "team_b_country"
] = "Northern Ireland"

elo_tourney.loc[
    (elo_tourney["team_a_country"] == old_name) &
    (elo_tourney["date"] > cutoff_date),
    "team_a_country"
] = "Republic of Ireland"

elo_tourney.loc[
    (elo_tourney["team_b_country"] == old_name) &
    (elo_tourney["date"] > cutoff_date),
    "team_b_country"
] = "Republic of Ireland"

In [58]:
matches_merged.loc[
    (matches_merged["home_team"] == matches_merged["team_a_country"] )
]

NameError: name 'matches_merged' is not defined

In [ ]:
set_difference2 = elo_tourney_set - matches_set
set_difference2

{'Aden',
 'Belgian Congo',
 'Bohemia',
 'Bohemia and Moravia',
 'Bonaire',
 'British Guiana',
 'British Honduras',
 'Burma',
 'Ceylon',
 'Commonwealth of Independent States',
 'Comoros',
 'Congo-Brazzaville',
 'Congo-Leopoldville',
 'Czechoslovakia',
 'Dahomey',
 'Dutch East Indies',
 'East Germany',
 'FS Micronesia',
 'Faroe Islands',
 'French Guiana',
 'French Somaliland',
 'French Togoland',
 'Gold Coast',
 'Greenland',
 'Guadeloupe',
 'Ireland',
 'Khmer Republic',
 'Korea',
 'Kosovo',
 'Macao',
 'Macedonia',
 'Malaya',
 'Mali Federation',
 'Martinique',
 'Mauritania',
 'Mayotte',
 'Monaco',
 'Netherlands Antilles',
 'New Hebrides',
 'North Vietnam',
 'North Yemen',
 'Northern Cyprus',
 'Northern Mariana Islands',
 'Northern Rhodesia',
 'Nyasaland',
 'Papua New Guinea',
 'Reunion',
 'Rhodesia',
 'Ruanda-Urundi',
 'Saar',
 'Saint Barthelemy',
 'Saint Martin',
 'Serbia and Montenegro',
 'Sint Eustatius',
 'Sint Maarten',
 'South Vietnam',
 'South Yemen',
 'Southern Rhodesia',
 'Soviet Union',
 'Surinam',
 'Swaziland',
 'Tahiti',
 'Tanganyika',
 'Tibet',
 'Tuvalu',
 'United Arab Republic',
 'Upper Volta',
 'West Germany',
 'Western Samoa',
 'Yugoslavia',
 'Zaire',
 'Zanzibar'}

In [ ]:
elo_tourney["score_pair"] = elo_tourney.apply(  #we create score pair column in elo tourney dataframe, then we apply..
    lambda row: tuple( #for each row we're creating a tuple, (?)
        score for country, score in sorted([ 
            (row["team_a_country"], row["team_a_score"]), #assigning/  accessing  for each row in country and score 
            (row["team_b_country"], row["team_b_score"])
        ])
    ),
    axis=1
)

matches["score_pair"] = matches.apply(
    lambda row: tuple (
        score for country, score in sorted([
            (row["home_team"], row["home_score"]),
            (row["away_team"], row["away_score"])
        ])
    ),
    axis = 1 
)

matches["country_pair"] = matches[["home_team", "away_team"]].apply(
    lambda row:  tuple(sorted(row)), axis = 1
)

elo_tourney["country_pair"] = elo_tourney[["team_a_country", "team_b_country"]].apply(
    lambda row: tuple(sorted(row)), axis = 1
)

In [ ]:
elo_tourney_set = set(np.concatenate([elo_tourney["team_a_country"], elo_tourney["team_b_country"]]))

matches_set - elo_tourney_set

{'Namibia'}

In [ ]:
len(overlap)

29840

In [ ]:
matches_merged = pd.merge(matches, elo_tourney, on = comp_key, how = "left")


matches_merged.tail(10)

,date,home_team,away_team,home_score,away_score,tournament_x,city,country,neutral,country_pair,...,tournament_y,team_a_rating,team_b_rating,team_a_rank,team_b_rank,tourney_code,tourney_name,tournament_bucket,team_a_country,team_b_country
34539,2026-07-07,Argentina,Egypt,3.0,2.0,FIFA World Cup,Atlanta,United States,True,"(Argentina, Egypt)",...,WC,2156.0,1742.0,2.0,34.0,WC,World Cup,FIFA World Cup,Argentina,Egypt
34540,2026-07-07,Switzerland,Colombia,0.0,0.0,FIFA World Cup,Vancouver,Canada,True,"(Colombia, Switzerland)",...,WC,2003.0,1949.0,5.0,11.0,WC,World Cup,FIFA World Cup,Colombia,Switzerland
34541,2026-07-09,France,Morocco,2.0,0.0,FIFA World Cup,Foxborough,United States,True,"(France, Morocco)",...,WC,2163.0,1901.0,2.0,14.0,WC,World Cup,FIFA World Cup,France,Morocco
34542,2026-07-10,Spain,Belgium,2.0,1.0,FIFA World Cup,Inglewood,United States,True,"(Belgium, Spain)",...,WC,2190.0,1948.0,1.0,11.0,WC,World Cup,FIFA World Cup,Spain,Belgium
34543,2026-07-11,Norway,England,1.0,2.0,FIFA World Cup,Miami Gardens,United States,True,"(England, Norway)",...,WC,2097.0,1951.0,4.0,9.0,WC,World Cup,FIFA World Cup,England,Norway
34544,2026-07-11,Argentina,Switzerland,3.0,1.0,FIFA World Cup,Kansas City,United States,True,"(Argentina, Switzerland)",...,WC,2177.0,1928.0,2.0,11.0,WC,World Cup,FIFA World Cup,Argentina,Switzerland
34545,2026-07-14,France,Spain,0.0,2.0,FIFA World Cup,Arlington,United States,True,"(France, Spain)",...,WC,2232.0,2121.0,1.0,3.0,WC,World Cup,FIFA World Cup,Spain,France
34546,2026-07-15,England,Argentina,1.0,2.0,FIFA World Cup,Atlanta,United States,True,"(Argentina, England)",...,WC,2200.0,2074.0,2.0,4.0,WC,World Cup,FIFA World Cup,Argentina,England
34547,2026-07-18,France,England,4.0,6.0,FIFA World Cup,Miami Gardens,United States,True,"(England, France)",...,WC,2125.0,2070.0,3.0,4.0,WC,World Cup,FIFA World Cup,England,France
34548,2026-07-19,Spain,Argentina,1.0,0.0,FIFA World Cup,East Rutherford,United States,True,"(Argentina, Spain)",...,WC,2259.0,2173.0,1.0,2.0,WC,World Cup,FIFA World Cup,Spain,Argentina

In [ ]:
matches_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34549 entries, 0 to 34548
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               34549 non-null  datetime64[ns]
 1   home_team          34549 non-null  object
 2   away_team          34549 non-null  object
 3   home_score         34549 non-null  float64
 4   away_score         34549 non-null  float64
 5   tournament_x       34549 non-null  object
 6   city               34549 non-null  object
 7   country            34549 non-null  object
 8   neutral            34549 non-null  bool
 9   country_pair       34549 non-null  object
 10  score_pair         34549 non-null  object
 11  team_a             29840 non-null  object
 12  team_b             29840 non-null  object
 13  team_a_score       29840 non-null  float64
 14  team_b_score       29840 non-null  float64
 15  tournament_y       29840 non-null  object
 16  team_a_rating      29840 non-null  float64
 17  team_b_rating      29840 non-null  float64
 18  team_a_rank        29840 non-null  float64
 19  team_b_rank        29840 non-null  float64
 20  tourney_code       29840 non-null  object
 21  tourney_name       29840 non-null  object
 22  tournament_bucket  29840 non-null  object
 23  team_a_country     29840 non-null  object
 24  team_b_country     29840 non-null  object
dtypes: bool(1), datetime64[ns](1), float64(8), object(15)
memory usage: 6.4+ MB

In [ ]:
len(matches)

34549

In [ ]:
len(matches_merged)

34549

In [ ]:
matches_merged.to_csv("../data/processed/matches_elo_merged_raw.csv")

In [ ]:
matches_merged[
    ["home_team", "away_team", "team_a_country", "team_b_country", 
    "team_a_rating", "team_b_rating"]
].tail()

,home_team,away_team,team_a_country,team_b_country,team_a_rating,team_b_rating
34544,Argentina,Switzerland,Argentina,Switzerland,2177.0,1928.0
34545,France,Spain,Spain,France,2232.0,2121.0
34546,England,Argentina,Argentina,England,2200.0,2074.0
34547,France,England,England,France,2125.0,2070.0
34548,Spain,Argentina,Spain,Argentina,2259.0,2173.0

In [ ]:
matches_merged.loc[
    (matches_merged["home_team"] == matches_merged["team_a_country"]),
    "home_elo"
] = matches_merged["team_a_rating"]


matches_merged.loc[
    (matches_merged["away_team"] == matches_merged["team_b_country"]),
    "away_elo"
] = matches_merged["team_b_rating"]


matches_merged.loc[
    (matches_merged["home_team"] == matches_merged["team_b_country"]),
    "home_elo"
] = matches_merged["team_b_rating"]

matches_merged.loc[
    (matches_merged["away_team"] == matches_merged["team_a_country"]),
    "away_elo"
] = matches_merged["team_a_rating"]

In [ ]:
matches_merged.isna().sum()

date                    0
home_team               0
away_team               0
home_score              0
away_score              0
tournament_x            0
city                    0
country                 0
neutral                 0
country_pair            0
score_pair              0
team_a               4709
team_b               4709
team_a_score         4709
team_b_score         4709
tournament_y         4709
team_a_rating        4709
team_b_rating        4709
team_a_rank          4709
team_b_rank          4709
tourney_code         4709
tourney_name         4709
tournament_bucket    4709
team_a_country       4709
team_b_country       4709
home_elo             4709
away_elo             4709
dtype: int64

In [ ]:
matches_merged[
    ["home_team", "away_team", "team_a_country", "team_b_country", 
    "team_a_rating", "team_b_rating", "home_elo", "away_elo"]
].tail()

,home_team,away_team,team_a_country,team_b_country,team_a_rating,team_b_rating,home_elo,away_elo
34544,Argentina,Switzerland,Argentina,Switzerland,2177.0,1928.0,2177.0,1928.0
34545,France,Spain,Spain,France,2232.0,2121.0,2121.0,2232.0
34546,England,Argentina,Argentina,England,2200.0,2074.0,2074.0,2200.0
34547,France,England,England,France,2125.0,2070.0,2070.0,2125.0
34548,Spain,Argentina,Spain,Argentina,2259.0,2173.0,2259.0,2173.0

In [ ]:
matches_merged.loc[
    (matches_merged["home_team"] == matches_merged["team_a_country"]),
    "home_ranking"
] = matches_merged["team_a_rank"]

matches_merged.loc[
    (matches_merged["away_team"] == matches_merged["team_b_country"]),
    "away_ranking"
] = matches_merged["team_b_rank"]

matches_merged.loc[
    (matches_merged["home_team"] == matches_merged["team_b_country"]),
    "home_ranking"
] = matches_merged["team_b_rank"]

matches_merged.loc[
    (matches_merged["away_team"] == matches_merged["team_a_country"]),
    "away_ranking"
] = matches_merged["team_a_rank"]

In [ ]:
matches_merged[
    ["home_team", "away_team", "team_a_country", "team_b_country", 
    "team_a_rating", "team_b_rating", "home_elo", "away_elo", "team_a_rank", "team_b_rank"]
].tail()

,home_team,away_team,team_a_country,team_b_country,team_a_rating,team_b_rating,home_elo,away_elo,team_a_rank,team_b_rank
34544,Argentina,Switzerland,Argentina,Switzerland,2177.0,1928.0,2177.0,1928.0,2.0,11.0
34545,France,Spain,Spain,France,2232.0,2121.0,2121.0,2232.0,1.0,3.0
34546,England,Argentina,Argentina,England,2200.0,2074.0,2074.0,2200.0,2.0,4.0
34547,France,England,England,France,2125.0,2070.0,2070.0,2125.0,3.0,4.0
34548,Spain,Argentina,Spain,Argentina,2259.0,2173.0,2259.0,2173.0,1.0,2.0

In [ ]:
cols_to_drop = ["country_pair", 
                "score_pair", "team_a", "team_b", "team_a_score", 
                "team_b_score", "team_a_rating", "team_b_rating",
                "team_a_rank", "team_b_rank", "team_a_country", "team_b_country", 
                "tournament_x", "tourney_code"]

matches_merged = matches_merged.drop(columns=cols_to_drop)

KeyError: "['country_pair', 'score_pair', 'team_a', 'team_b', 'team_a_score', 'team_b_score', 'team_a_rating', 'team_b_rating', 'team_a_rank', 'team_b_rank', 'team_a_country', 'team_b_country', 'tournament_x', 'tourney_code'] not found in axis"

In [ ]:
matches_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34549 entries, 0 to 34548
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               34549 non-null  datetime64[ns]
 1   home_team          34549 non-null  object
 2   away_team          34549 non-null  object
 3   home_score         34549 non-null  float64
 4   away_score         34549 non-null  float64
 5   city               34549 non-null  object
 6   country            34549 non-null  object
 7   neutral            34549 non-null  bool
 8   tournament_y       29840 non-null  object
 9   tourney_name       29840 non-null  object
 10  tournament_bucket  29840 non-null  object
 11  home_elo           29840 non-null  float64
 12  away_elo           29840 non-null  float64
 13  home_ranking       29840 non-null  float64
 14  away_ranking       29840 non-null  float64
dtypes: bool(1), datetime64[ns](1), float64(6), object(7)
memory usage: 3.7+ MB

In [ ]:
matches_merged = matches_merged.drop(columns = ["tourney_name"])

In [ ]:
matches_merged.tail(10)

,date,home_team,away_team,home_score,away_score,city,country,neutral,tournament_y,tournament_bucket,home_elo,away_elo,home_ranking,away_ranking
34539,2026-07-07,Argentina,Egypt,3.0,2.0,Atlanta,United States,True,WC,FIFA World Cup,2156.0,1742.0,2.0,34.0
34540,2026-07-07,Switzerland,Colombia,0.0,0.0,Vancouver,Canada,True,WC,FIFA World Cup,1949.0,2003.0,11.0,5.0
34541,2026-07-09,France,Morocco,2.0,0.0,Foxborough,United States,True,WC,FIFA World Cup,2163.0,1901.0,2.0,14.0
34542,2026-07-10,Spain,Belgium,2.0,1.0,Inglewood,United States,True,WC,FIFA World Cup,2190.0,1948.0,1.0,11.0
34543,2026-07-11,Norway,England,1.0,2.0,Miami Gardens,United States,True,WC,FIFA World Cup,1951.0,2097.0,9.0,4.0
34544,2026-07-11,Argentina,Switzerland,3.0,1.0,Kansas City,United States,True,WC,FIFA World Cup,2177.0,1928.0,2.0,11.0
34545,2026-07-14,France,Spain,0.0,2.0,Arlington,United States,True,WC,FIFA World Cup,2121.0,2232.0,3.0,1.0
34546,2026-07-15,England,Argentina,1.0,2.0,Atlanta,United States,True,WC,FIFA World Cup,2074.0,2200.0,4.0,2.0
34547,2026-07-18,France,England,4.0,6.0,Miami Gardens,United States,True,WC,FIFA World Cup,2070.0,2125.0,4.0,3.0
34548,2026-07-19,Spain,Argentina,1.0,0.0,East Rutherford,United States,True,WC,FIFA World Cup,2259.0,2173.0,1.0,2.0

In [ ]:
matches_merged.columns
matches_merged = matches_merged.rename(columns = {"tournament_y": "tournament_code", "tournament_bucket": "tournament"})

In [ ]:
matches_merged.columns

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score', 'city',
       'country', 'neutral', 'tournament_code', 'tournament', 'home_elo',
       'away_elo', 'home_ranking', 'away_ranking'],
      dtype='object')

In [ ]:
matches_merged.to_csv("../data/processed/matches_elo_merged_processed.csv")